ROOT = ..
SOURCES = binarize enhace_grayscale lbpFeatures2 lbpFeatures lbpTransform

# MISSING COMPONENTS cannot locate __bilde.hpp__
# wi_retrieve connected_components_labeling test_png

# textline_segment is throwing many errors on compilation. May be a problem with my installation

# Libraries to dynamically link
LIBS := opencv_ml opencv_objdetect opencv_stitching opencv_superres opencv_videostab opencv_calib3d opencv_features2d opencv_highgui opencv_video opencv_photo opencv_imgproc opencv_flann opencv_core IexMath protobuf webp png tiff jasper Imath IlmImf Iex Half IlmThread uuid lzma jpeg z

include $(ROOT)/common.mk
